server:
  port: 9999
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root@123456
    hikari:
      # 连接池最大连接数，默认是10
      maximum-pool-size: 15
      # 最小空闲连接数量
      minimum-idle: 5
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      # 连接池名称
      pool-name: HikariPool
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      location: /tmp/run.halo.app
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  level:
    run.halo.app: INFO
  file:
    path: ${user.home}/.halo/logs

halo:
  download-timeout: 5m
  # Your admin client path is https://your-domain/{admin-path}
  admin-path: admin
  # memory, level, redis
  cache: memory
  # if cache = redis, you need to set the following options
  # cache-redis-nodes: ['122.51.137.215:6379']
  # cache-redis-password: redis_123456